import { validateSlip, type SlipLeg } from "./slipValidation";

export const demoSlipLegs: SlipLeg[] = [
    {
        id: "tatum-points",
        eventId: "bos-nyk",
        sport: "NBA",
        marketType: "Player Points",
        marketFamily: "Player Points",
        entityType: "player",
        entityId: "jayson-tatum",
        teamId: "bos",
        opponentTeamId: "nyk",
        playerId: "jayson-tatum",
        statType: "points",
        timeScope: "full_game",
        side: "Over",
        selection: "25+",
        line: 25,
        sameGameEligible: true,
    },
    {
        id: "tatum-assists",
        eventId: "bos-nyk",
        sport: "NBA",
        marketType: "Player Assists",
        marketFamily: "Player Assists",
        entityType: "player",
        entityId: "jayson-tatum",
        teamId: "bos",
        opponentTeamId: "nyk",
        playerId: "jayson-tatum",
        statType: "assists",
        timeScope: "full_game",
        side: "Over",
        selection: "5+",
        line: 5,
        sameGameEligible: true,
    },
    {
        id: "knicks-plus",
        eventId: "bos-nyk",
        sport: "NBA",
        marketType: "Point Spread",
        marketFamily: "Point Spread",
        entityType: "team",
        entityId: "nyk",
        teamId: "nyk",
        opponentTeamId: "bos",
        statType: "spread",
        timeScope: "full_game",
        side: "away",
        selection: "Knicks +7.5",
        line: 7.5,
        sameGameEligible: true,
    },
];

export const demoSlipValidationResult = validateSlip(demoSlipLegs);
